name: Node.js TypeScript API CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  SERVER_HOST: 103.193.178.16
  SERVER_USER: ridwanFatur
  APP_PATH: /home/ridwanFatur/simple-node-js
  DOCKER_REPO: ridwanfatur/simple-node-js:1.0

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Create .env file
        run: |
          echo "PORT=3000" > .env

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ env.DOCKER_REPO }}

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ env.SERVER_HOST }} >> ~/.ssh/known_hosts

      - name: Update Docker on server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.SERVER_HOST }}
          username: ${{ env.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd ${{ env.APP_PATH }}
            docker-compose down
            docker pull ${{ env.DOCKER_REPO }}
            docker-compose up -d		

      - name: Deployment Status
        run: echo "Deployment completed successfully!"