name: Node.js TypeScript API CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build
      run: npm run build
      
    - name: Create .env file
      run: |
        echo "PORT=3000" > .env
    - name: Setup SSH Key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H 103.59.95.208 >> ~/.ssh/known_hosts
    - name: Deploy to Server via SSH
      uses: appleboy/ssh-action@master
      with:
        host: 103.59.95.208
        username: ridwanFatur
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          mkdir -p /home/ridwanFatur/simple_nodejs
          rm -rf /home/ridwanFatur/simple_nodejs/*
          mkdir -p /home/ridwanFatur/simple_nodejs/dist			
    - name: Copy dist folder to server
      run: |
        scp -r ./dist/* ridwanFatur@103.59.95.208:/home/ridwanFatur/simple_nodejs/dist/
        scp .env ridwanFatur@103.59.95.208:/home/ridwanFatur/simple_nodejs/
        scp package.json ridwanFatur@103.59.95.208:/home/ridwanFatur/simple_nodejs/
    - name: Install dependencies and start app on server
      uses: appleboy/ssh-action@master
      with:
        host: 103.59.95.208
        username: ridwanFatur
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          cd /home/ridwanFatur/simple_nodejs
          npm install
    - name: Deployment Status
      run: echo "Deployment completed successfully!"